name = "parametricity"
version = "0.1.0"
defaultTargets = ["parametricity"]

[[lean_lib]]
name = "Parametricity"

#[[require]]
#name = "mathlib"
#scope = "leanprover-community"
#rev = "v4.17.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
